name: Weekly Threat Group Post

on:
  schedule:
    - cron: '0 12 * * 1' # Every Monday at 12:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install rss-parser fs-extra node-fetch dayjs dotenv

      - name: Run weekly threat group script
        run: node tools/auto-cyber-posting/generate-threat-group-post.js
        env:
          HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}

      - name: Commit & push
        run: |
          git config user.name "sleep33-bot"
          git config user.email "bot@sleep33.dev"
          git add _posts
          git commit -m "🕵️ Weekly threat group post"
          git push
